// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tviludfrwkbgkdcycgdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2aWx1ZGZyd2tiZ2tkY3ljZ2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDM0OTYsImV4cCI6MjA2MzgxOTQ5Nn0.PoD6wEEGJszu0SsO784XgiRIFNHoazAkKASte9a_MYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);